### ISSUE TITLE
Script Crash

### ISSUE THREAD

**Issue by kaosity** [Amrsatrio/BlenderUmap#10]
Blender crashes after running the script.

**Comment by AP05-Yeet** [comment]
same

**Comment by geekn00b** [comment]
same

**Comment by nordfilmou** [comment]
This is because you processed multiple umap files at once. Test to process one at a time, that is, for each umap you process with the tool, you run the blender script.

After importing, delete the folders created by the script, and only then, process the next Umap.

It worked for me!

**Comment by AP05-Yeet** [comment]
Okay thank you very much 😊

**Comment by geekn00b** [comment]
was because i didnt put the pakchunk1006 key now its working
