### ISSUE TITLE
my blender crashes when I run the script

### ISSUE THREAD

**Issue by geekn00b** [Amrsatrio/BlenderUmap#11]
my blender crashes when I run the script

**Comment by nordfilmou** [comment]
This is because you processed multiple umap files at once. Test to process one at a time, that is, for each umap you process with the tool, you run the blender script.

After importing, delete the folders created by the script, and only then, process the next Umap.

It worked for me!

**Comment by geekn00b** [comment]
was because i didnt put the pakchunk1006 key now its working
