### ISSUE TITLE
BlenderUmap Error, Uncaught exception when running the Batch File 

### ISSUE THREAD

**Issue by Ham1987** [Amrsatrio/BlenderUmap#13]
![hlp](https://user-images.githubusercontent.com/51301822/86049832-23915380-ba53-11ea-9567-d9c773b03652.PNG)

**Comment by dayoshiguy** [comment]
this happened to me too. help?

**Comment by dayoshiguy** [comment]
i updated my jave to the latest 64 bit version and the problem got fixed
