### ISSUE TITLE
VALORANT maps look pretty blocky

### ISSUE THREAD

**Issue by SpieleFresser** [Amrsatrio/BlenderUmap#15]
The first screenshot shows how Bonsai_Art_BTower.umap looks, the second the config.json file. 
Umap version 0.2.1 (with version 0.1.1 everything works fine), Java 64 bit installed, .psk import plugin for Blender installed and activated, used newest AES Key available.

If I change the bReadMaterials to false - same result

If I delete the lines:
 ,
{
    "FileName": ...
    "Key": ...
}
- same result

If I use Unreal Engine version 4.23 in UModel and in the config script of Umap - it works

If I use Unreal Engine version 4.25 in UModel but change the config script of Umap to "UEVersion": "GAME_UE4_23", - it works

Also, there is an issue that Blender crashes once in a while when I run the python script but that's just annoying and could be caused by my PC, not your script.
![blocky Btower](https://user-images.githubusercontent.com/48879937/86770631-3efeee80-c051-11ea-83e2-83f9fc4325f2.png)
![config script](https://user-images.githubusercontent.com/48879937/86770665-5047fb00-c051-11ea-8388-1cddfc442ddc.png)

**Comment by floxay** [comment]
works fine for me? also I don't get why would you touch umodel or set anything to 4.25, valorant is on 4.23
![image](https://user-images.githubusercontent.com/57007485/86947751-7ef6cc00-c14c-11ea-9910-d054cc891e56.png)
![image](https://user-images.githubusercontent.com/57007485/86947778-87e79d80-c14c-11ea-816d-a8ebcd457079.png)

**Comment by SpieleFresser** [comment]
Ok, I didn't know that VALORANT is in 4.23. I didn't change the UE version of the config script. The version I downloaded had "GAME_UE4_25" in it so I assumed that this would be the correct version.

**Comment by AP05-Yeet** [comment]
Press resolve if its done
