### ISSUE TITLE
Every mesh is stacked on each other

### ISSUE THREAD

**Issue by Ayeggs** [Amrsatrio/BlenderUmap#16]
I have been trying to import fortnite umaps but every single one that I try ends up with every mesh being stacked on each other.
![everythingisstacked](https://user-images.githubusercontent.com/68455242/87844606-c0922000-c88c-11ea-8cf9-23cfe32d5a9c.PNG)

**Comment by Amrsatrio** [comment]
> Make sure you have the Blender PSK import/export plugin at least version 2.7.13 installed. If you use prior versions of the plugin the scaling of the props will appear broken

You have to make sure that it is the latest version because it fixed scaling of imported PSKs.
