### ISSUE TITLE
Invalid escape sequence in $.Paksdirectory

### ISSUE THREAD

**Issue by KarikFreiheit** [Amrsatrio/BlenderUmap#23]
I checked and the path to the Paks for Valorant was right, I don’t know what else to do. I’m able to use UModel so the path should work but it doesn’t seem to be. Java 64 bit is installed. 
![image](https://user-images.githubusercontent.com/56356629/90838841-ce631700-e30a-11ea-83d5-624d09be0aec.jpg)
![image](https://user-images.githubusercontent.com/56356629/90838859-db800600-e30a-11ea-80a9-6ba563b4b5a7.jpg)

**Comment by Amrsatrio** [comment]
Use double backslashes
