### ISSUE TITLE
we could not reserve enough space for 3145728kb

### ISSUE THREAD

**Issue by Marhzyy** [Amrsatrio/BlenderUmap#29]
we could not reserve enough space for 3145728kb object heap 
press any key to continue , , , 
This happens when i run the BlenderUmap.Bat file and i dont know how to fix it

**Comment by xKrasheR** [comment]
same here

**Comment by MrMadTitan** [comment]
same

**Comment by AP05-Yeet** [comment]
same

**Comment by Amrsatrio** [comment]
Uninstall 32 bit java and install the 64 bit one. Or remove -Xmx3G in the bat
