### ISSUE TITLE
Doesn't work with Fortnite 1.8 (ue 4.16)

### ISSUE THREAD

**Issue by YoshiCrystal** [Amrsatrio/BlenderUmap#30]
As the title says, it doesn't work with Fortnite 1.8, it could be that the umodel version that it uses doesn't support that version. I have an older umodel that works with this version but still doesn't work with BlenderUmap

**Comment by lefishingrestore** [comment]
I had this same issue with 10.4

**Comment by Amrsatrio** [comment]
Fortnite versions before Chapter 2 arent guaranteed to be supported and at this time there will be no plans to support them.
