### ISSUE TITLE
Season 2

### ISSUE THREAD

**Issue by Tamely** [Amrsatrio/BlenderUmap#34]
I am trying to export umaps from season 2, I have all the paks, aes, and version right on the config, but when I try to do it, it throws an error (see pic) then stops. This only happens on season 2, on the current one, it works perfectly.
![unknown-92](https://user-images.githubusercontent.com/64652542/96469102-75bcd700-11f2-11eb-8f89-ed9e298487a1.png)
![unknown-192](https://user-images.githubusercontent.com/64652542/96469105-77869a80-11f2-11eb-91c0-dffa23964890.png)

**Comment by AP05-Yeet** [comment]
same

**Comment by AP05-Yeet** [comment]
it happens with everything for me

**Comment by Amrsatrio** [comment]
Sorry, but there will be no plans yet to add support for very old UE4 versions, either by me or the maintainers of JFortniteParse.
