### ISSUE TITLE
Could not reserve enough space for 3145728KB object heap

### ISSUE THREAD

**Issue by FissionMetroid101** [Amrsatrio/BlenderUmap#9]
Whenever I attempt to run the bat file, I end up getting this error.  It says there's an error with the initialization of the VM before the object heap bit.  Any key following will close the command prompt.  I am running on Windows 7 64-bit, and have 16 gigs of RAM.

**Comment by Amrsatrio** [comment]
Uninstall java 32 bit and install the 64 bit one

**Comment by FissionMetroid101** [comment]
Ahh, many thanks!  I thought the 64 bit version would've been the default judging by the OS.  The scripts worked like an absolute charm now <3
